

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault
  namespace: tanzu-continuousdelivery-resources 
spec:
  interval: 10m0s
  provider: generic
  timeout: 60s
  url: https://helm.releases.hashicorp.com

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: tanzu-continuousdelivery-resources 
spec:
  releaseName: vault-secrets-operator
  targetNamespace: vault-secrets-operator
  interval: 10m
  chart:
    spec:
      chart: vault-secrets-operator
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: tanzu-continuousdelivery-resources 
---

