namespace: tanzu-system-service-discovery
deployment:
  args:
  - --source=service
  - --provider=cloudflare
  - --domain-filter=onshore.place
  - --domain-filter=tanzu.rocks
  - --domain-filter=surferslookout.com
  - --policy=upsert-only
  - --registry=txt
  - --txt-owner-id=default
  - --txt-prefix=txt
  env:
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: platform-credentials
        key: cloudflare_token
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: platform-credentials
        key: cloudflare_username
  securityContext: {}
  volumeMounts: []
  volumes: []
