---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cadvisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged 
subjects:
- kind: ServiceAccount
  name: prometheus-node-exporter-sa
  namespace: tanzu-system-monitoring
