---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: prometheus
  namespace: tkg-system
spec:
  serviceAccountName: pkg-gitops-pkgi-sa
  packageRef:
    refName: prometheus.tanzu.vmware.com
    versionSelection:
      constraints: 2.37.0+vmware.3-tkg.1
  values:
  - secretRef:
      name: prometheus-packages-values