apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-tap-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: tanzu.packages.broadcom.com/tanzu-application-platform/tap-packages:${tapversion}

---

apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: full-deps-package-repo
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: tanzu.packages.broadcom.com/tanzu-application-platform/full-deps-package-repo:${tapversion}
 
