apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tap-install
spec:
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: ${tapversion}
      prereleases: {}
  serviceAccountName: tap-gitops-sa
  values:
  - secretRef:
      name: tap-packages-values