---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-node-exporter-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:tanzu-system-privileged 
subjects:
- kind: ServiceAccount
  name: prometheus-node-exporter-sa
  namespace: tanzu-system-monitoring

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-tkg-admin-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:tanzu-system-privileged 
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
