# tap-registry

apiVersion: v1
kind: Secret
metadata:
  name: tap-registry
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${pivnet_dockerjson_base64}

--- 

apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-registry
  namespace: tap-install
spec:
  toNamespace: '*'
  toNamespaces:
  - '*'

---

# registry-credentials

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${harbor_home_dockerjson_base64}

--- 

apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry-credentials
  namespace: tap-install
spec:
  toNamespace: '*'
  toNamespaces:
  - '*'


---

# lsp-registry-credentials

apiVersion: v1
kind: Secret
metadata:
  name: lsp-registry-credentials
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${registry_dockerjson_base64}

--- 

apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: lsp-registry-credentials
  namespace: tap-install
spec:
  toNamespace: '*'
  toNamespaces:
  - '*'

---

# supply-chain-oci-store-credentials
# stores persistent data between supplychain stages 

apiVersion: v1
kind: Secret
metadata:
 name: supply-chain-oci-store-credentials
 namespace: tap-install
type: Opaque
stringData:
 ocistore.yaml: |
   tanzusupplychain:
     ocistore:
       username: ${registry_username}
       password: ${registry_password}
       server: ${registry_host}
       repository: ${registry_project}


---
