
# git-access

apiVersion: v1
kind: Secret
metadata:
    name: git-access
    namespace: tap-install
type: Opaque
stringData:
    username: ${git_username}
    password: ${git_token}

---

# git-auth

apiVersion: v1
kind: Secret
metadata:
    name: git-auth
    namespace: tap-install
type: Opaque
stringData:
    content.yaml: |
        git:
            host: https://${gitops_host}/
            username: ${git_username}
            password: ${git_token}


---

# git-auth-overlay

apiVersion: v1
kind: Secret
metadata:
    name: git-auth-overlay
    namespace: tap-install
    annotations:
        kapp.k14s.io/change-rule: "delete after deleting tap"
stringData:
    git-auth-overlay.yaml: |
        #@ load("@ytt:overlay", "overlay")
        #@overlay/match by=overlay.subset({"apiVersion": "v1", "kind": "ServiceAccount","metadata":{"name":"default"}}), expects="0+"
        ---
        secrets:
        #@overlay/append
        - name: git
