
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: common-foundation
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 5m0s
  path: clustergroups/common/foundation
  postBuild:
    substitute:
      clustergroup: apa-tap
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: platform-gitops

---
