--- 

apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: tap-config
  namespace: tanzu-continuousdelivery-resources
spec:
  appName: tap3-config
  destination:
    create: true
    labels:
      hvs: "true"
    name: tap-config
  refreshAfter: 10m