
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tap-prepare
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 5m0s
  path: packages/services/tap/prepare
  postBuild:
    substituteFrom:
      - kind: Secret
        name: platform-credentials
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: platform-gitops

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tap-config
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
  - name: tap-prepare
    namespace: tanzu-continuousdelivery-resources
  interval: 5m0s
  path: packages/services/tap/personas/tap5.tanzu.rocks/config
  postBuild:
    substituteFrom:
      - kind: Secret
        name: platform-credentials
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: platform-gitops

---
