

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-nfs-helm-repo
  namespace: tanzu-continuousdelivery-resources 
spec:
  interval: 10m0s
  provider: generic
  timeout: 60s
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

--- 

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-nfs-driver
  namespace: tanzu-continuousdelivery-resources 
spec:
  interval: 10m0s
  chart:
    spec:
      chart: csi-driver-nfs
      version: '*'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-nfs-helm-repo
        namespace: tanzu-continuousdelivery-resources 
