apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yml
- serviceaccount.yml
- secretimport.yml
- ../../cert-manager/issuers/cloudflare-issuer.yml  
