--- 

apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: vso-sp
  namespace: tap-install
spec:
  fromNamespace: platform-gitops

--- 

apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: platform-credentials
  namespace: tap-install
spec:
  appName: platform-credentials
  destination:
    create: true
    labels:
      hvs: "true"
    name: platform-credentials
  refreshAfter: 10m
  
---

