apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: supply-chain-custom
secrets:
  - name: registry-credentials
  - name: git-creds
  - name: tap-registry
imagePullSecrets:
  - name: registry-credentials
  - name: tap-registry

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-deliverable
  namespace: supply-chain-custom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable
subjects:
  - kind: ServiceAccount
    name: default
    
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-workload
  namespace: supply-chain-custom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
  - kind: ServiceAccount
    name: default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: supplychain-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-cluster-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: supply-chain-custom

--- 
