apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: default
spec:
  delegations:
    - secretName: tap-cert
      targetNamespaces:
        - "*"
