apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: full-tbs-deps
  namespace: tap-install
spec:
  packageRef:
    refName: full-deps.buildservice.tanzu.vmware.com
    versionSelection:
      constraints: '> 0.0.0'
      prereleases: {}
  serviceAccountName: tap-gitops-sa
  values:
  - secretRef:
      name: tap-packages-values
