# credentials saved in secret store

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tap-gitops-config
  namespace: tanzu-continuousdelivery-resources
data:
  dnsname: tap1.tanzu.rocks
  tapversion: 1.11.1
  gitops_host: github.com
  gitops_owner: davlloyd
  gitops_repo: home-tap-gitops
  gitops_workload_repo: tap-gitops-1
  registry_host: harbor.tanzu.rocks
  registry_project: tap
  profile: full
  ns_additions: additions    # Support for supplychain versus cartographer supported additions
  s3_url: https://minio.home.local:9000    # credentials saved in secret store under s3_accessid and s3_accesskey
  s3_region: au-syd-1
